"""
portfolio_generator.py
----------------------
ResumeIQ — Portfolio Generation Engine

Responsibility:
- Generate a one-page, mobile-responsive portfolio website
- Use structured profile (and optional resume)
- Persist portfolio HTML in MongoDB

NO ATS logic
NO parsing
NO PDF rendering
"""

from datetime import datetime
from typing import Dict, Any, Optional
import os

from bson import ObjectId
from dotenv import load_dotenv

from profile_repository import get_profile_by_id

# ------------------------------
# Environment & DB setup (shared single client)
# ------------------------------

load_dotenv()

from db import db

portfolios_collection = db["portfolios"]
resumes_collection = db["resumes"]

# ------------------------------
# HTML Template
# ------------------------------

def generate_portfolio_html(
    profile: Dict[str, Any],
    resume: Optional[Dict[str, Any]] = None
) -> str:
    """
    Generate a clean, responsive portfolio HTML page.
    """

    personal = profile["structured"].get("personal", {})
    skills = profile["structured"].get("skills", [])
    projects = profile["structured"].get("projects", [])
    experience = profile["structured"].get("experience", [])
    education = profile["structured"].get("education", [])
    links = profile["structured"].get("links", {})

    name = personal.get("name", "Student Portfolio")

    html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{name} | Portfolio</title>
<style>
body {{
  font-family: -apple-system, BlinkMacSystemFont, Arial, sans-serif;
  margin: 0;
  padding: 0;
  line-height: 1.6;
  background: #ffffff;
  color: #111;
}}
header {{
  padding: 48px 24px;
  background: #0b0f1a;
  color: #fff;
  text-align: center;
}}
section {{
  padding: 40px 24px;
  max-width: 960px;
  margin: auto;
}}
h1, h2 {{
  margin-bottom: 16px;
}}
h2 {{
  border-bottom: 2px solid #eee;
  padding-bottom: 6px;
}}
.skill {{
  display: inline-block;
  margin: 6px 8px 6px 0;
  padding: 6px 12px;
  border-radius: 999px;
  background: #f2f2f2;
  font-size: 14px;
}}
.card {{
  margin-bottom: 24px;
}}
.footer {{
  padding: 24px;
  text-align: center;
  font-size: 14px;
  color: #666;
}}
a {{
  color: #2563eb;
  text-decoration: none;
}}
</style>
</head>
<body>

<header>
  <h1>{name}</h1>
  <p>{personal.get("location", "")}</p>
  <p>
    {f'<a href="{links.get("github")}">GitHub</a>' if links.get("github") else ""}
    {f' | <a href="{links.get("linkedin")}">LinkedIn</a>' if links.get("linkedin") else ""}
  </p>
</header>

<section>
  <h2>Skills</h2>
  {"".join(
      f"<div><strong>{s['category']}:</strong> "
      + " ".join(f'<span class="skill">{i}</span>' for i in s['items'])
      + "</div>"
      for s in skills
  )}
</section>

<section>
  <h2>Projects</h2>
  {"".join(
      f"<div class='card'><h3>{p['title']}</h3>"
      f"<p>{p['description']}</p>"
      f"<p><em>Technologies:</em> {', '.join(p.get('technologies', []))}</p></div>"
      for p in projects
  )}
</section>

<section>
  <h2>Experience</h2>
  {"".join(
      f"<div class='card'><strong>{e['role']}</strong> — {e['organization']}<br>"
      f"<small>{e['duration']}</small><p>{e['details']}</p></div>"
      for e in experience
  )}
</section>

<section>
  <h2>Education</h2>
  {"".join(
      f"<p><strong>{e['degree']}</strong>, {e['institution']} ({e['year']})</p>"
      for e in education
  )}
</section>

<div class="footer">
  Generated by ResumeIQ • SentIQ AI Labs
</div>

</body>
</html>
"""
    return html


# ------------------------------
# Public API
# ------------------------------

def generate_portfolio(
    profile_id: str,
    resume_id: Optional[str] = None
) -> Dict[str, Any]:
    """
    Generate and store a portfolio website.

    Args:
        profile_id: MongoDB profile ID
        resume_id: Optional resume ID for enhancement

    Returns:
        Stored portfolio document
    """

    profile = get_profile_by_id(profile_id)
    if not profile:
        raise ValueError("Profile not found")

    resume = None
    if resume_id:
        resume = resumes_collection.find_one({"_id": ObjectId(resume_id)})

    html = generate_portfolio_html(profile, resume)

    portfolio_doc = {
        "profile_id": ObjectId(profile_id),
        "resume_id": ObjectId(resume_id) if resume_id else None,
        "html": html,
        "created_at": datetime.utcnow()
    }

    result = portfolios_collection.insert_one(portfolio_doc)
    portfolio_doc["_id"] = str(result.inserted_id)
    portfolio_doc["profile_id"] = profile_id
    portfolio_doc["resume_id"] = resume_id
    
    # Convert datetime to ISO string for JSON serialization
    portfolio_doc["created_at"] = portfolio_doc["created_at"].isoformat()

    return portfolio_doc


# ------------------------------
# Optional local test
# ------------------------------

if __name__ == "__main__":
    TEST_PROFILE_ID = "PUT_PROFILE_ID_HERE"
    portfolio = generate_portfolio(TEST_PROFILE_ID)
    print("Portfolio generated:", portfolio["_id"])
